### ISSUE TITLE
[Bug]: cannot find 'casefold' in the module 'material.plugins.tags.plugin'

### ISSUE THREAD

**Issue by BorderCloud** [eccenca/documentation.eccenca.com#119]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/eccenca/documentation.eccenca.com/blob/main/CONTRIBUTING.md) and wholeheartedly agree.

### Description

When I build the project (branch 23.1) with the command  `task serve`, I have the error:
```
task: [install] poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: documentation-eccenca-com (0.0.0)
task: [serve] poetry run mkdocs serve
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find 'casefold' in the module 'material.plugins.tags.plugin'
  in "/home/karima/git/doc/mkdocs.yml", line 271, column 21
task: Failed to run task "serve": exit status 1
```

### Expected behaviour

No error with the command `task serve`.

**Comment by irangareddy** [comment]
Plugins are only available with [MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/?h=plugin#built-in-plugins). If you refer to the [taskfile](https://github.com/eccenca/documentation.eccenca.com/blob/main/Taskfile.yml), you will discover three tasks related to the use of mkdocs setup.
```
  use:public:
    desc: switch to public package (non insider)

  use:insider-ssh:
    desc: switch to insider package from github:eccenca via ssh (default)

  use:insider-https-token:
    desc: switch to insider package from github:eccenca via ACCESS_TOKEN variable (build plan)
```
If necessary, request @seebi to send you an invitation to join @eccenca/documentation

**Comment by seebi** [comment]
@BorderCloud I invited you to the documentation group thus I can close this ticket ...
